{% set name = "icepap" %}
{% set version = "3.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icepap-{{ version }}.tar.gz
  sha256: cd957de6077f7885d933513566e48c97b035eecb546649350a21b4c722a82c4c

build:
  number: 0
  noarch: python
  entry_points:
    - icepap = icepap.__main__:main
    - icepapctl = icepap.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - beautifultable >=1
    - click >=7
    - numpy
    - prompt_toolkit >=3
    - python >=3.6

test:
  requires:
    - pip
  imports:
    - icepap
  commands:
    - pip check
    - icepap --help
    - icepapctl --help

about:
  home: https://github.com/ALBA-Synchrotron/pyIcePAP
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Python IcePAP Extension
  description: |
    Python module to configure, control and monitor IcePAP based systems.
    IcePAP is a motor control system developed at the ESRF and optimised
    for high resolution position applications.
  doc_url: https://alba-synchrotron.github.io/pyIcePAP-doc/
  dev_url: https://github.com/ALBA-Synchrotron/pyIcePAP

extra:
  recipe-maintainers:
    - beenje
